/**
 * Creating a sidebar
 *
 * It can be generated from the filesystem, or manually.
 * Learn more: https://docusaurus.io/docs/sidebar#sidebar-create-a-sidebar-from-a-single-file
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate sidebar from the docs folder structure
    },
  ],
  // Alternatively, create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;